hmcts/pip-publication-services

charts/pip-publication-services/values.yaml

https://tools.hmcts.net/jira/browse/PUB-762
Add the secrets into the AKS
```
[ ] Yes
[X  ] No
```

Pub-762 add secrets

---

src/test/resources/application.yaml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

removed useless testing key

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/notify/TemplatesTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-928
Added new notify endpoint to send provenance and location ID from unidentified blobs, these are sent by data management in the daily cron job to the new endpoint.
```
[ ] Yes
[x] No
```

PUB-928 - Handle receipt of unidentified blob

---

config/owasp/suppressions.xml

N/A
Added supressions
```
[ ] Yes
[x] No
```

Added supressions

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Artefact.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/ArtefactType.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Language.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Location.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/Sensitivity.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1437
Send header information given in ticket to third party
[ ] Yes
[x] No

PUB-1437 Send Headers to third party

---

charts/pip-publication-services/Chart.yaml
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java

N/A
Fixed integration tests
```
[ ] Yes
[x] No
```

Fixed integration tests

---

src/main/java/uk/gov/hmcts/reform/pip/publication/services/helpers/EmailHelper.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/helpers/EmailHelperTest.java

https://tools.hmcts.net/jira/browse/PUB-1478
Updated logs to mask email
```
[ ] Yes
[x] No
```

PUB-1478 - Updated logs

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/helpers/MultiPartHelper.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/helpers/MultiPartHelperTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1485
Send multi part request body for flat file to third party API
```
[ ] Yes
[x] No
```

PUB-1485 Send multi part request body for flat file to third party API

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1525
Updated so that CSV files are sent successfully
```
[ ] Yes
[x] No
```

PUB-1525 - Updated sending for CSV

---

src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientConfiguration.java

N/A
Updated file limit to 2MB
```
[ ] Yes
[x] No
```

Updated limit for files to 2MB

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementService.java

Updated to x-admin
```
[ ] Yes
[x] No
```

Get publication fix

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PUB-1486
Updated the default URLs in application.yaml for the custom domains in staging change.
```
[ ] Yes
[x] No
```

PUB-1486 Updated defaults

---

src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java

Updated template ID to correct one.
```
[ ] Yes
[x] No
```

Update template ID

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/external/ListType.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/templatemodels/PrimaryHealthList.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/PrimaryHealthList.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/SjpPublicList.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/converters/PrimaryHealthListConverter.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/converters/SjpPublicListConverter.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/DailyCauseListHelper.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/DateHelper.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/LocationHelper.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/listmanipulation/PrimaryHealthListManipulation.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/listmanipulation/SjpManipulation.java
src/main/resources/templates/languages/cy/primaryHealthList.json
src/main/resources/templates/languages/en/primaryHealthList.json
src/main/resources/templates/primaryHealthList.html
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/ArtefactSummaryServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/artefactsummary/PrimaryHealthListTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/converters/PrimaryHealthListConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/DataManipulationTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/DateHelperTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/LocationHelperTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/filegeneration/helpers/listmanipulation/SjpManipulationTest.java
src/test/resources/mocks/primaryHealthList.json

https://tools.hmcts.net/jira/browse/PUB-1472
Add Primary Health Tribunal list PDF and artefact summary generation。
```
[ ] Yes
[x] No
```

PUB-1472 Add Primary Health tribunal PDF and artefact summary generation

---

Dockerfile
build.gradle
config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientFunctionalTestConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientTestConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/configuration/WebClientTestConfiguration.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1678
Upgraded publication services from Java 11 to 17.
```
[ ] Yes
[x] No
```

PUB-1678 Java 17 upgrade

---

build.gradle
config/owasp/suppressions.xml

N/A
Update suppressions
```
[ ] Yes
[x] No
```

Updated suppressions

---

Dockerfile
build.gradle
config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientTestConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/configuration/WebClientTestConfiguration.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/AccountManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/DataManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/SubscriptionManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyServiceTest.java

N/A
PR to merge Freeze to Master
```
[ ] Yes
[x] No
```

Merge Freeze to Master

---

build.gradle
config/owasp/suppressions.xml

N/A
Added suppressions due to being on latest version + already part of spring.
```
[ ] Yes
[x] No
```

Fixed dependencies

---

src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/exceptions/ThirdPartyServiceException.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/helpers/MultiPartHelper.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/FileCreationService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/validation/SubscriptionsConstraintValidator.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/helpers/EmailHelperTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1741
Fix sonarCloud code smells
```
[ ] Yes
[x] No
```

PUB-1751 Fix sonarCloud code smells

---

charts/pip-publication-services/Chart.yaml

N/A
Updated Helm version
```
[ ] Yes
[x] No
```

Updated Helm version

---

charts/pip-publication-services/Chart.yaml

N/A
Update Helm to latest
```
[ ] Yes
[x] No
```

Update helm to 4.0.11

---

build.gradle

N/A
Update OWASP version
```
[ ] Yes
[x] No
```

Updated OWASP dependency version

---

infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PUB-1811
Remove unneeded variables
```
[ ] Yes
[x] No
```

PUB-1811 - Removed unneeded variables

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1898
Added content date to the subs email.
Note: The template IDs will need changing back before merging and the test ones deleted from notify.
```
[ ] Yes
[x] No
```

PUB-1898 Content date in subs email

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java

https://tools.hmcts.net/jira/browse/PUB-1910
Update dependencies + suppressions
```
[ ] Yes
[x] No
```

PUB-1910 - Update dependencies

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java

N/A
Updated artefact ID to fix pipeline
```
[ ] Yes
[x] No
```

Updated test file

---

config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java

https://tools.hmcts.net/jira/browse/PUB-1924
Fix tests with blob deletion in staging
```
[ ] Yes
[x] No
```

PUB-1924 Fix tests with blob deletion in staging

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-1991
Updated to retrigger build
```
[ ] Yes
[x] No
```

PUB-1991 - Updated gradle

---

src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/GlobalExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/UserNotificationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/notify/TemplatesTest.java

https://tools.hmcts.net/jira/browse/PUB-1732
Update logging
```
[ ] Yes
[x] No
```

PUB-1732 Update logging

---

build.gradle
charts/pip-publication-services/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-1996
Update dependencies
```
[ ] Yes
[x] No
```

PUB-1996 - Updated dependencies

---

build.gradle
src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebClientConfiguration.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ChannelManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/ThirdPartyManagementServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1960
Fix subscription email not sent if PDF file over 2MB
```
[ ] Yes
[x] No
```

PUB-1960 Fix subscription email not sent if PDF file over 2MB

---

build.gradle

N/A
Updated vulnerability
```
[ ] Yes
[x] No
```

Fixed vulnerability

---

build.gradle
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java

https://tools.hmcts.net/jira/browse/PUB-2054
Add SJP delta press list (new cases)
```
[ ] Yes
[X] No
```

Pub 2054 - Add SJP delta press list

---

build.gradle
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationService.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/PersonalisationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1974
Display list type friendly name in subscription email
```
[ ] Yes
[x] No
```

PUB-1974 Display list type friendly name in subscription email

---

Dockerfile
Jenkinsfile_nightly
README.md
charts/pip-publication-services/values.yaml
lib/AI-Agent.xml
lib/applicationinsights.json
src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/WebConfiguration.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PUB-2084
Updated App Insights version
Updated App Insights to use connection string
```
[ ] Yes
[x] No
```

PUB-2084 - Updated App Insights to use connection string

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-2153
Update pip-data-models to add OPA Press List listType
```
[ ] Yes
[x] No
```

PUB-2153 Add OPA Press List listType

---

infrastructure/tf-apim-logger.tf

https://tools.hmcts.net/jira/browse/PUB-2193
Add APIM logging
```
[ ] Yes
[x] No
```

PUB-2193 Add APIM logging

---

infrastructure/resources/api-policy/api-policy.xml
infrastructure/resources/operation-policies/sendOtpEmail.xml
infrastructure/resources/operation-policies/welcome.xml
infrastructure/tf-apim-api.tf
infrastructure/tf-apim-operations.tf

https://tools.hmcts.net/jira/browse/PUB-2193
Fixed key vault location
```
[ ] Yes
[ ] No
```

PUB-2193 Fixed key vault location

---

.github/workflows/terraform_format.yml
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/providers.tf
infrastructure/stg.tfvars
infrastructure/test.tfvars
infrastructure/tf-apim-api.tf
infrastructure/tf-apim-operations.tf

https://tools.hmcts.net/jira/browse/PUB-2182
Add terraform_format.yml
```
[ ] Yes
[X] No
```

PUB-2182 add terraform_format.yml

---

.github/workflows/terraform_format.yml
README.md
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/providers.tf
infrastructure/stg.tfvars
infrastructure/test.tfvars
infrastructure/tf-apim-api.tf
infrastructure/tf-apim-operations.tf

Merge code freeze branch to Master
```
[ ] Yes
[x] No
```

Merge code freeze branch to Master

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-2208
Update pip-data-models version for OPA results
```
[ ] Yes
[x] No
```

PUB-2208 Update pip-data-models version for OPA results

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/SpringSecurityConfig.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/configuration/SpringSecurityConfigTest.java

https://tools.hmcts.net/jira/browse/PUB-2133
Updated version of spring boot
```
[ ] Yes
[x] No
```

PUB-2133 - Updated version of spring boot

---

Jenkinsfile_nightly
README.md
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/PUB-1619
Enable Fortify on the nightly pipeline
```
[ ] Yes
[x] No
```

PUB-1619 - Enable fortify on nightly

---

Jenkinsfile_nightly

https://tools.hmcts.net/jira/browse/PUB-1619
Updated KV
```
[ ] Yes
[x] No
```

Updated KV name

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-1619
Added fortify library classifier
```
[ ] Yes
[x] No
```

PUB-1619 - Added fortify library classifier

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-2363
Update Data Models version number
```
[X] Yes
[ ] No
```

PUB-2363 - Update Data Models version number

---

Dockerfile
README.md
build.gradle

https://tools.hmcts.net/jira/browse/PUB-2461
Upgrading to Java 21
```
[ ] Yes
[x] No
```

PUB-2461: Upgrading to Java 21

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PUB-2546
Lower the size limit that decides when follow up files should be retrieved 
```
[ ] Yes
[x] No
```

PUB-2545 - Lower file generation limit

---

infrastructure/resources/operation-policies/sendOtpEmail.xml

https://tools.hmcts.net/jira/browse/PUB-2535
Updated to handle both body and header for authorization APIM
```
[ ] Yes
[x] No
```

PUB-2535 - Updated to handle both body and header

---

infrastructure/resources/operation-policies/sendOtpEmail.xml

https://tools.hmcts.net/jira/browse/PUB-2535
Part 2 - Change to only have Authorization
```
[ ] Yes
[x] No
```

PUB-2535 - Updated APIM

---

infrastructure/resources/operation-policies/sendOtpEmail.xml

https://tools.hmcts.net/jira/browse/PUB-2535
Change validate-jwt back to using the request body
```
[ ] Yes
[x] No
```

PUB-2535 - Updated validate-jwt

---

infrastructure/resources/operation-policies/sendOtpEmail.xml

https://tools.hmcts.net/jira/browse/PUB-2535
Testing in Test Env
```
[ ] Yes
[x] No
```

PUB-2535 - Updated validate JWT

---

infrastructure/resources/operation-policies/sendOtpEmail.xml

https://tools.hmcts.net/jira/browse/PUB-2633
Change back perftest
```

PUB-2633 - Change back perftest

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyRateLimitTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyTest.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/models/emaildata/reporting/SystemAdminUpdateEmailData.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/notify/Templates.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/EmailService.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/reporting/SystemAdminUpdateEmailGenerator.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/NotificationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/emailgeneration/reporting/SystemAdminUpdateEmailGeneratorTest.java

https://tools.hmcts.net/jira/browse/PUB-2681
Updated System Admin update email to use email instead of name
```
[ ] Yes
[x] No
```

PUB-2681 - Updated System Admin Alert

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-2712
Add CIC Daily Hearing List
```
[ ] Yes
[x] No
```

PUB-2712 Add CIC Daily Hearing List 

---

src/functionalTest/java/uk/gov/hmcts/pip/publication/services/NotificationEmailTests.java

https://tools.hmcts.net/jira/browse/PUB-2568
Added new functional tests to notify end points
```
[ ] Yes
[x] No
```

Added new functional tests to notify end points

---

charts/pip-publication-services/Chart.yaml

https://tools.hmcts.net/jira/browse/PUB-2827
Updated helm chart
```
[ ] Yes
[x] No
```

PUB-2827 - Updated helm chart

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-2899
Updated to Azure DevOps
```
[ ] Yes
[x] No
```

PUB-2899 - Updated to AzureDevOps

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-2896
Add a new list type
```
[ ] Yes
[x] No
```

PUB-2896 - Added new list type

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-2981
Updated spring version
```
[ ] Yes
[x] No
```

PUB-2981 - Updated spring

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-2960
Add Magistrates Adult Court List
```
[ ] Yes
[x] No
```

PUB-2960 Add Magistrates Adult Court List

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-2965
Removed CIC list
```
[ ] Yes
[x] No
```

PUB-2965 - Remove CIC list

---

Jenkinsfile_CNP
build.gradle
charts/pip-publication-services/Chart.yaml
charts/pip-publication-services/values.dev.template.yaml
charts/pip-publication-services/values.stg.template.yaml
charts/pip-publication-services/values.yaml
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/pip/publication/services/BatchNotificationEmailTests.java
src/functionalTest/java/uk/gov/hmcts/pip/publication/services/NotificationEmailTests.java
src/functionalTest/java/uk/gov/hmcts/pip/publication/services/SubscriptionNotificationEmailTests.java
src/functionalTest/java/uk/gov/hmcts/pip/publication/services/config/AwsS3ConfigurationFunctional.java
src/functionalTest/java/uk/gov/hmcts/pip/publication/services/utils/FunctionalTestBase.java
src/functionalTest/java/uk/gov/hmcts/pip/publication/services/utils/OAuthClient.java
src/functionalTest/resources/data/testFile.html
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/config/AwsS3ConfigurationTestConfiguration.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotifyAwsS3BucketTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/publication/services/utils/IntegrationTestBase.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/config/AwsS3Configuration.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationController.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/errorhandling/exceptions/S3UploadException.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/helpers/MultiPartHelper.java
src/main/java/uk/gov/hmcts/reform/pip/publication/services/service/AwsS3Service.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pip/publication/services/controllers/NotificationControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/helpers/MultiPartHelperTest.java
src/test/java/uk/gov/hmcts/reform/pip/publication/services/service/AwsS3ServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2844
Upload HTML from PDDA and push to S3 bucket
[ ] Yes
[x] No

PUB-2844 Upload HTML from PDDA and push to S3 bucket
